In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
physical_activity =  "../../data/Physical_activity.csv"
physical_activity_df = pd.read_csv(physical_activity)
physical_activity_df.head()

,Year,LocationAbbr,Location,Question,Data_Value,Low_Confidence,High_Confidence,Sample_Size,Age(years),Gender,Race/Ethnicity
0,2020,US,National,Percent of adults who engage in no leisure-tim...,30.6,29.4,31.8,31255.0,NaN,NaN,Hispanic
1,2015,US,National,Percent of adults who achieve at least 300 min...,26.6,25.6,27.6,30904.0,NaN,NaN,NaN
2,2015,GU,Guam,Percent of adults who achieve at least 150 min...,27.4,18.6,38.5,125.0,NaN,NaN,Hispanic
3,2015,PR,Puerto Rico,Percent of adults who engage in no leisure-tim...,38.1,32.6,43.8,421.0,NaN,NaN,NaN
4,2015,GU,Guam,Percent of adults who engage in no leisure-tim...,30.5,25.8,35.6,559.0,NaN,NaN,NaN

In [11]:
physical_activity_clean = physical_activity_df[["Year","LocationAbbr", "Question", "Data_Value", "Gender"]]
physical_activity_clean = physical_activity_clean.loc[physical_activity_clean['Year']==2020]
physical_activity_clean = physical_activity_clean.groupby("Gender")
physical_activity_clean.head()

,Year,LocationAbbr,Question,Data_Value,Gender
13,2020,ME,Percent of adults who engage in no leisure-tim...,21.7,Male
33,2020,SD,Percent of adults who engage in no leisure-tim...,22.6,Male
154,2020,NJ,Percent of adults who engage in no leisure-tim...,23.0,Female
1933,2020,GA,Percent of adults who engage in no leisure-tim...,27.6,Female
1948,2020,MS,Percent of adults who engage in no leisure-tim...,34.0,Female
1950,2020,CO,Percent of adults who engage in no leisure-tim...,18.1,Female
1974,2020,HI,Percent of adults who engage in no leisure-tim...,21.7,Female
1975,2020,UT,Percent of adults who engage in no leisure-tim...,13.9,Male
2027,2020,NY,Percent of adults who engage in no leisure-tim...,23.4,Male
2037,2020,GU,Percent of adults who engage in no leisure-tim...,21.6,Male

In [18]:
states = ["ME","SD","NJ","GA","MS"]
mean_value = []

# physical_by_State
for state in states:
     state_match_s = physical_activity_clean["LocationAbbr"] == state
     state_match_value_s = physical_activity_clean[state_match_s,'LocationAbbr']    
    # add subset to tumor_vol_data
mean_value.append(state_match_value_s)

mean_value

C:\Users\MishkisPCDell\AppData\Local\Temp\ipykernel_5132\2616621572.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  state_match_value_s = physical_activity_clean[state_match_s,'LocationAbbr']

KeyError: 'Columns not found: False'